### PR TITLE
Optimize recursive expansion

### PR DESCRIPTION
**Pull request by sje397**
I have a dataset with about 200 nodes, which is rather deep rather than flat.

With the old code, it takes around 20 seconds to 'expandAll'. With this improvement it takes less than a second.

By profiling it turns out that most of the time was spent in the `expandSomeNodes' method. This is because the method traces up to the root for every node in the tree - making it an exponential time operation.

With this change, expansion goes only once from the selected node up the tree, and from the selected node downward.

### CODE REVIEW

**Comment by bumbeishvili** [comment]
Thanks, I don't know when but at some point I'll take a detailed look at it and will see if I can integrate new solution

**Comment by sje397** [comment]
Sure thing. It's certainly not perfect - I was just trying to make the website I was building work with that data set. For example I don't think the call to `expandParents` on line 1255 is necessary. You can see it working here if you like: https://zenmarrow.com/LineageChart.html

Thank you for a wonderful js lib.

**Comment by dlgoodchild** [comment]
(this comment has nothing to do with the issue mentioned)
@sje397 how did you go about changing the line colours of the links? I've been looking but they all appear hardcoded. I'm looking for a way to save me having to fork and modify the code (though I'll go that route if necessary). Sorry to hijack the issue...

**Comment by bumbeishvili** [comment]
@dlgoodchild take a look at this issue, this is a relevant one 

https://github.com/bumbeishvili/org-chart/issues/208

**Comment by dlgoodchild** [comment]
Thanks @bumbeishvili I just came across that and so deleted my comment/question. Typical, to come across it seconds after posting. You were pretty fast there though!

**Comment by bumbeishvili** [comment]
@sje397 thanks for the pointer.

I found an underlying issue and made the change.  Tested it for  500 nodes ( Hierarchy level was also linear 500 level deep). And result was instantaneous expand, so hoping it will be the same for you

image

It will be included in v3 version of the org chart, which I'll release soon

**Pull request closed without merging**
