### PR TITLE
3.0 Version of org chart

### LINKED ISSUE #23: Pagination /showing fixed number of nodes in each level
Hi I am using the older version of this project [link](https://bl.ocks.org/bumbeishvili/dbc0beff4baf64674b0f05b94cb4462e).
but if a node has 40-50 children the view gets cluttered an you have to scroll left/right too much.

I was wondering if there is an easy way to shown "n" number of nodes on each level and will have previous next button to show the next n.

from my understanding this isn't currently implemented in the code right now, so I am looking for any pointers / previous work to start.

### LINKED ISSUE #69: Examples => Safari Issue
Safari is unable to correctly render foreignObject elements, where content is overflowing.

And it leads to [weird issues](https://twitter.com/dbumbeishvili/status/1425745088341291010).

First two examples should be free of this issue, since I made sure that they would not overflow specified dimensions (so it should be safe to reuse in case safari support is important)

### LINKED ISSUE #80: Improve overall event handling
Currently, it's not much user friendly

### LINKED ISSUE #103: Chart instance methods and attributes documentation
Thanks for this libaray. I think it has some good potential.

Is there any intention to improve it's documentation, especially documentation of public methods and attributes of the chart instance?

### LINKED ISSUE #113: Typo - neightbourMargin
There is a typo in attrs object

### LINKED ISSUE #123: get the real-time zoom level when zooming the chart
Hi, thanks for your library, it works great.
but I have some questions,
1. the chart.lastTrasform().k provided the zoom level, but is it a way to get the zoom event when I am zooming the chart by using the touchpad ?  
another questions :
2. Does this chart has destroy or dispose method ?
3. I wanted to recover the chart to initial zoom level(1) after zoomed the chart, is it possible to make it?

### LINKED ISSUE #124: callback 'onNodeClick' was triggered when clicking the collapse/expand button in Safari
**Describe the bug**
callback 'onNodeClick' was triggered when clicking the collapse/expand button in Safari
**To Reproduce**
1. wirte some code in onNodeClick function
2. Click on expand button
3. the code was excuted

**Expected behavior**
I wanted to jump to other page when clicking the node, but  it also jumped to other page when I was just clicking the expand/collapse button in Safari, 
**Screenshots**
image

**Desktop (please complete the following information):**
 - OS:  macos 10.15.7  macos 12.2.1
 - Browser safari
 - Version 15.3

### LINKED ISSUE #126: Group Nodes with no-childrens
**Is your feature request related to a problem? Please describe.**
For example, I can add A, B and C nodes. So, If I add ten A nodes, 10 B nodes and 10 C nodes I will have a bigger graph on the screen.

**Describe the solution you'd like**
Is there any way to group all of these A, B and C nodes (30 in totals, 10 for each of them) in only 3 groups? So, If I add a children node to any A node, I will see A with this new children, a group for A's (with 8 more A's), a group for B's (with 9 B's) and a group for C's (with 9 C's)

---

### LINKED ISSUE #137: How to not have rounded edged on joining lines
i am trying to reduce the curve on the edges of the lines that connect my cards, i checked all the examples but couldnt find how they did it so please help. In the screenshots below u can see how it looks rightnow(more curved) vs how i want it to look like
Screenshot 2022-03-29 at 11 47 02 AM
 
Screenshot 2022-03-29 at 11 46 53 AM

### LINKED ISSUE #139: Can we change default onload depth of tree?
Can we change default on-load depth of the chart?

for example currently it shows 1 layer of sub-nodes as soon as the page loads
can we make it 3 or maybe even 4?

like currently when i load the page is loads like this
Screenshot-2022-04-07-at-1 44 51-PM

whereas i want it to load like this
Screenshot-2022-04-07-at-1 42 53-PM

### LINKED ISSUE #154: setExpanded" won't allow you to close a node that was open by user clicking.
image

### LINKED ISSUE #162: Do you have or plan json support?
Hello,

Very interesting your project but why csv? You need to have those ids in order to know the connection between object.
Why not a imbricated json? Do you have support for something like this or do you plan to add ?
Thanks

### LINKED ISSUE #169: Trying to stop zooming
Hello,

I'm trying to stop zooming on scroll when mouse over item in the node which is overflow and need to be scrolled up/down. maybe even stop panning too for mobile when pointer on the same overflow object.

Any suggestion?
Best regards.

### LINKED ISSUE #170: Initial node push and addNode working differently
**Describe the bug**
Because of the different nature of initial value comparison and addNode value comparison if the id's of the records are numeric (integer) addNode complains about can't find the parentId in nodes.

**To Reproduce**
1. parse data with integer type of id and parentId values
2. Its working on initial render
3. try to add new node on runtime using addNode method with integer or string id and parentId values

**Expected behavior**
Initial node rendering and addNode method need to behave same nature.

**Additional context**
on addNode method convert to string on both comparison can fix the problem.
```
const nodeFound = attrs.allNodes.filter(({ data }) => attrs.nodeId(data).toString() === attrs.nodeId(obj).toString())[0];
const parentFound = attrs.allNodes.filter(({ data }) => attrs.nodeId(data).toString() === attrs.parentNodeId(obj).toString())[0];
```

### LINKED ISSUE #173: Is it possible to delete root on runtime?
Hello,

I can delete all nodes runtime but root node. It give "no root" error on console.

Any suggestion?
Best regards.

### LINKED ISSUE #204: Simple way to expand level?
Before submitting an issue, please make sure to check whether the similar question was asked before. 
You can search for it here - https://github.com/bumbeishvili/d3-organization-chart/issues

Hey there, Ive done some navigating through the code, and I am trying to find an easy way to expand to a certain level without doing too much iteration. 

Basically on load, I would like to expand the the 3rd level. Is there a simple way to do this?

### LINKED ISSUE #206: How to expand / collapse node dynamically?
var node = d3.select("#" + d); // d = id

How can I **expand** or **collapse** this specific node without having the user to click on the node button?

    chart.expand(node); // not working
    chart.setExpanded(d); // not working

And if possible, check the state whether it is expanded or collapsed later

### LINKED ISSUE #207: Why is clearHighlighting() not returning this?
clearHighlighting() {
        const attrs = this.getChartState();
        attrs.allNodes.forEach(d => {
            d.data._highlighted = false;
            d.data._upToTheRootHighlighted = false;
        })
        this.update(attrs.root)
        // return this; // to make it consistant
    }

### LINKED ISSUE #211: Discrepancy with typescript definition for onNodeClick
**Describe the bug**
The typescript definition for `onNodeClick` shows `onNodeClick(): (node: HierarchyNode<Datum>) => void;` - [Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-org-chart/index.d.ts#L165)

The actual code is invoked with the nodeId - https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L812

This is a bug because the attr definition also hints that this is supposed to be a node object - https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L95

Sending a node is more consistent with the other callback functions as well, instead of just the nodeId.

**Expected behavior**
The correct/consistent implementation [for this line](https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L812) would be `attrs.onNodeClick(data);`

### LINKED ISSUE #215: Bug found with Sky chart.
**Describe the bug**
Under specific conditions the joining line does not properly connect to some of the children of a parent. 

**To Reproduce**
Request the following CSV file in your chart, using the **sky** chart. This will not properly display once you drill down and open all the child elements.  

https://raw.githubusercontent.com/twillisCFB/public/main/sample.csv 

**Expected behavior**
Line should connect to all children of any parent element. 

**Screenshots**
image

**Desktop (please complete the following information):**
Issue is present on Chrome and Edge. Others not tested.

**Additional context**
Problem only occurs if this specific layout is selected, we have tried other templates and they work as expected.

### LINKED ISSUE #238: The org cannot have two or more people as supreme leader
**Describe the bug**
when there are two or more people as a leader the library doesn't work

### LINKED ISSUE #259: Drag and click event confusion
Sometimes node is clicked, but the drag event is firing. Need to address this

### LINKED ISSUE #269: Add a hook to wait for the completion of fit
Greetings.
I think it would be useful to have a way to know when a `fit()` operation has actually concluded instead of having to rely on timeouts.
D3 transitions natively provides a `end()` method which returns a `Promise`: https://observablehq.com/@d3/transition-end.
Similar hooks could be useful in other spots I am not aware of.

### LINKED ISSUE #290: `onNodeClick` impacts node collapse/expand behaviour
`onNodeClick` when implemented to highlight the clicked node seems to screw up node collapse/expand behaviour. Collapsed nodes seem to fly off the top of the screen instead of being collapsed into the parent, and on expansion again every child that was expanded is shown collapsed, so they all have to be expanded again one by one.

```
    .onNodeClick((d) => {
      chart.clearHighlighting();
      chart.setHighlighted(d.id).render();
    })
```

This method is firing on the node even when just clicking expand/collapse, so I think there is some auto-expansion happening inside the `setHighlighted` call, but I'm not sure. Can we avoid firing this method as well when the expand/collapse button is clicked?

### LINKED ISSUE #306: SVG Export: Uncaught ReferenceError: h is not defined
[Description]
When using export SVG function reports an error when used:
`
d3-org-chart@3.0.1-next.1:69 Uncaught ReferenceError: h is not defined
    at t.OrgChart.downloadImage (d3-org-chart@3.0.1-next.1:69:24027)
    at t.OrgChart.exportSvg (d3-org-chart@3.0.1-next.1:69:23585)
    at HTMLButtonElement.onclick ((index):1:7)
`

1. Go to [example page for export function](https://stackblitz.com/edit/js-ue1cpj?file=index.html)
2. Click on EXPORT SVG button

Expected behavior: Download SVG file

Desktop
 - OS: Mac
 - Browser: chrome

### PR DESCRIPTION
**Pull request by bumbeishvili**
## Breaking changes
* Fixed typo in chart state property name, so <code>neigh**t**bourMargin</code> became `neighbourMargin` (closes #113)
* Attached property  `_directSubordinates` now only shows nodes which are visible, if we want to also get info about hidden nodes (because of paging), we can use `_directSubordinatesPaging`
* `onNodeClick` method now returns data instead of node id
* renamed `expandLevel` to `initialExpandLevel`, from now on the user can configure the level/depth at which nodes will open initially (closes #238 )(closes #204) (closes #139)
## New Features
* Added paging [feature](https://stackblitz.com/edit/js-pr15gr?file=index.html) for nodes with many horizontal children. (Closes #23 , closes #126)
* Node count is now visible by default 
  image

## Fixes
* Closes #306 - Move functions at the top to help minifier correctly interpret the flow
* Closes #290 - differentiate node click and expand collapse button click
* Closes #259 - Drag and click event confusion
* Closes #215 - Diagonal zero condition 
* Closes #211 - Discrepancy for onNodeClick
* Closes #206 - Typo 

## Improvements
* Closes #169 - added `createZoom` method to help with conditional zooming and scrollable content
* Added [new examples](https://github.com/bumbeishvili/org-chart/tree/d089f7b358b4d272737f7afbbdc517b51bb722e9#features) to showcase every distinct feature (closes #162 )
* [Wrote more](https://github.com/bumbeishvili/org-chart/tree/d089f7b358b4d272737f7afbbdc517b51bb722e9#installing) about the usage of the org chart and the functionality behind  (closes #103 )
* Made [`Styled Tree`](https://github.com/bumbeishvili/org-chart/tree/d089f7b358b4d272737f7afbbdc517b51bb722e9#features) example safari safe
* Examples now are using the better-structured [dataset](https://github.com/bumbeishvili/sample-data/blob/main/data-oracle.csv) 
* Made it easier to reliably override node expand & collapse button HTML (closes #69)(closes  #123)
* Made it easier to reliably override link path command generation algorithm (closes #137 )
* Zoom event notifications (closes #80 )
* Closes #269  - callback function to listen to `fit` function `end` event
* `_hierarchyHeight` property is added, which shows node height index within hierarchy (not actual height in pixels)
* Closes #207 - Make clear highlighting method consistent
* Closes #154 - `setExpanded(nodeId,false)` now also marks node siblings for collapse
* Closes #170 - all methods using node id's for comparison are more forgiving when you are passing different types (string, int)
* Closes #173 - Now it's possible to delete a root node at runtime 
* Closes #124 - add event.stopPropagation for nodeButton
* Make it possible to name the exported file using for example `chart.imageName('test').exportImg()`
* Improve performance for expandAll method when hierarchy is very deep (up to 500 level)

## Checks
* [x] Check that #221 PR is incorporated into this PR
* [x] Check that #222  PR is incorporated into this PR

### CODE REVIEW

**Comment by abinoda** [comment]
👏🏼

**Comment by m-gallesio** [comment]
Greetings.
Is native lazy loading (https://github.com/bumbeishvili/org-chart/issues/147) still planned / being considered?

**Comment by bumbeishvili** [comment]
It's planned but treat it as an idea only, I don't expect to have it done on the near future unless I will have an org-chart project involving that particular feature

**Comment by n1crack** [comment]
@bumbeishvili 
what do you think of adding a search button near the pagination button ? When you click a node it adds it immediately to the shown list. 

The pic is so bad but something like this would be perfect along with the pagination system. This way we can show only the data we want. 
 
image

**Comment by bumbeishvili** [comment]
Idea is interesting, but I am against it, since that UX does not seem familiar and will add additional burden which is not necessary.

**Comment by bumbeishvili** [comment]
That said it might make sense to expose methods which lets you control the node content and behavior for the show next 5 nodes button.
This way anyone will actually be able to implement the same functionality as in your image

**Comment by n1crack** [comment]
I think it is necessary. Lets say the root has 50 person, and I want to show spesific 3 person under it to examine. 

> That said it might make sense to expose methods which lets you control the node content and behavior for the show next 5 nodes button. This way anyone will actually be able to implement the same functionality as in your image

That would be nice. I would add a dropdown button/menu which has the direct subordinates, and the selected ones would be shown in the chart.

**Comment by bumbeishvili** [comment]
Yep, good idea. I will keep it in mind and can get to it    If I find time outside my full time job and paid side projects , probably not for another 4-6 months

**Pull request merged**
