### PR TITLE
enable dragging

### PR DESCRIPTION
**Pull request by majodu**

### CODE REVIEW

**Comment by beekhof** [comment]
@majodu I'd say this is unlikely to get merged given inclusion of so many orthogonal formatting changes (whitespace, brackets, quotes).

You're also missing  `d3-drag:d3`from the rollup command.

@bumbeishvili are you interested in a minimal version of this PR that just adds drag-and-drop?

**Comment by bumbeishvili** [comment]
@beekhof  I have an idea how to implement drag drop and would not merge other PRs with similar functionality . I have implemented it already in other private project and it certainly was not as simple as I would have imagined and I faced many issues. 

That said, if you want to give it a go, feel free and I can link that PR to relevant issues to that people can have a temporary solution

**Comment by beekhof** [comment]
It took a bit of debugging, but PR #307 seemed to work for me

**Comment by bumbeishvili** [comment]
Had a quick look. Not sure how it will behave in the new v3 version, since root.descendants() behaves differently and it only returns visible nodes (some nodes are hidden because of paging )

**Comment by riyasat-ali** [comment]
@beekhof How can we use that functionality of drag and drop for [PR](https://github.com/bumbeishvili/org-chart/pull/307)? Is there any Stackblitz or codesandbox for that?

@bumbeishvili

**Pull request closed without merging**
